const productos = [
  {
    title: "Café 01",
    price: 500,
    image: "cafe_01.jpg",
    category: "cafe",
    stock: 6,
    id: "1",
  },
  {
    title: "Café 02",
    price: 500,
    image: "cafe_02.jpg",
    category: "cafe",
    stock: 8,
    id: "2",
  },
  {
    title: "Café 03",
    price: 500,
    image: "cafe_03.jpg",
    category: "cafe",
    stock: 4,
    id: "3",
  },
  {
    title: "Café 04",
    price: 500,
    image: "cafe_04.jpg",
    category: "cafe",
    stock: 6,
    id: "4",
  },
  {
    title: "Café 05",
    price: 500,
    image: "cafe_05.jpg",
    category: "cafe",
    stock: 8,
    id: "5",
  },
  {
    title: "Frappuccino 01",
    price: 600,
    image: "frappuccino_01.jpg",
    category: "frappuccino",
    stock: 4,
    id: "6",
  },
  {
    title: "Frappuccino 02",
    price: 600,
    image: "frappuccino_02.jpg",
    category: "frappuccino",
    stock: 6,
    id: "7",
  },
  {
    title: "Frappuccino 03",
    price: 600,
    image: "frappuccino_03.jpg",
    category: "frappuccino",
    stock: 8,
    id: "8",
  },
  {
    title: "Frappuccino 04",
    price: 600,
    image: "frappuccino_04.jpg",
    category: "frappuccino",
    stock: 4,
    id: "9",
  },
  {
    title: "Frappuccino 05",
    price: 600,
    image: "frappuccino_05.jpg",
    category: "frappuccino",
    stock: 6,
    id: "10",
  },
  {
    title: "Té 01",
    price: 400,
    image: "te_01.jpg",
    category: "te",
    stock: 8,
    id: "11",
  },
  {
    title: "Té 02",
    price: 400,
    image: "te_02.jpg",
    category: "te",
    stock: 4,
    id: "12",
  },

  {
    title: "Té 03",
    price: 400,
    image: "te_03.jpg",
    category: "te",
    stock: 6,
    id: "13",
  },
  {
    title: "Té 04",
    price: 400,
    image: "te_04.jpg",
    category: "te",
    stock: 8,
    id: "14",
  },
  {
    title: "Té 05",
    price: 400,
    image: "te_05.jpg",
    category: "te",
    stock: 4,
    id: "15",
  },
];

export default productos;
